### ISSUE TITLE
HOSTs syntax

### ISSUE THREAD

**Issue by iam-py-test** [seanpm2001/Seanpm2001-DRM-Blocklist#2]
### Prerequisites

- [X] I verified that this is not an existing issue
- [X] This is not a question, poll, or discussion
- [X] I checked the documentation to understand that the issue I report is not a normal behavior

### Description

The filterlists in this repository end entries with `/`. As HOSTs files only list domains, this is not valid syntax:
```hosts
0.0.0.0 www.netflix.com/
```
Otherwise, it is valid syntax.
Thank you for the filterlists.

**Comment by seanpm2001** [comment]
Thank you for your help. I am new to this language. I will go and fix it right now.

**Comment by iam-py-test** [comment]
No worries.
Thanks
